-> start
=== start===
You find yourself in an unknown place...
You are not sure how you got here... 
You don't recall blacking out from getting drunk, but you suppose that if you did black out, you wouldnt remember... 
Either way, its probably best to find your way out of here...

-> DONE